### Get learning homepage
GET http://localhost:3000/api/users/1/learning_homepage
Accept: application/json

###

### Get module theme
# finished OOP refactor
GET http://localhost:3000/api/modules/6/theme
Accept: application/json

###

### Get concept tutorial
# finished OOP refactor
GET http://localhost:3000/api/concepts/22/tutorial
Accept: application/json


### Get concept quizzes
# finished OOP refactor
GET http://localhost:3000/api/concepts/21/quiz
Accept: application/json


### Get concept summary
GET http://localhost:3000/api/concepts/21/summary
Accept: application/json

###

### Submit quiz answer
POST http://localhost:3000/api/quiz/1/submit
Content-Type: application/json

{
  "userId": 1,
  "answer": "A"
}

###

### Get module reflection prompt
GET http://localhost:3000/api/modules/1/reflection
Accept: application/json

###

### Submit module reflection
POST http://localhost:3000/api/modules/1/reflection/submit
Content-Type: application/json

{
  "userId": 1,
  "response": "Learnt a lot from this module."
}

