### Get learning homepage
# finished OOP refactor
GET http://localhost:3000/api/modules/overview
Accept: application/json

###

### Get module theme
# finished OOP refactor
GET http://localhost:3000/api/modules/1/theme
Accept: application/json

###

### Get concept tutorial
# finished OOP refactor
GET http://localhost:3000/api/concepts/1/tutorial
Accept: application/json


### Get concept quizzes
# finished OOP refactor
GET http://localhost:3000/api/concepts/46/quiz
Accept: application/json


### Get concept summary
# finished OOP refactor
GET http://localhost:3000/api/concepts/46/summary
Accept: application/json

###

### Submit quiz answer
POST http://localhost:3000/api/quiz/91/answer
Content-Type: application/json

{
  "responseType": "single_choice",
  "userId": 7,
  "userAnswerIndices": [0],
  "timeSpend": 19
}

###

### Get module reflection prompt
# finished OOP refactor
GET http://localhost:3000/api/modules/1/reflection
Accept: application/json

###

### Submit module reflection
# finished OOP refactor
POST http://localhost:3000/api/modules/13/reflection
Content-Type: application/json

{
  "reflectionId": 12,
  "userId": 2,
  "answer": "Learnt a lot from this module.",
  "timeSpent": 999
}

###

### Update concept progress (Mark Concept 46 as Complete)
POST http://localhost:3000/api/concepts/46/progress
Content-Type: application/json

{
  "userId": 1,
  "isCompleted": true,
  "timeSpent": 120
}

###

### register a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "john@example.com",
  "username": "johndoe",
  "password": "Password123"
}

### login with email
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "emailOrUsername": "john@example.com",
  "password": "Password123"
}

### login with username
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "emailOrUsername": "johndoe",
  "password": "Password123"
}

### Get current user
GET http://localhost:3000/api/auth/me

### Logout
POST http://localhost:3000/api/auth/logout


