### Get learning homepage
# finished OOP refactor
GET http://localhost:3000/api/modules/overview
Accept: application/json

###

### Get module theme
# finished OOP refactor
GET http://localhost:3000/api/modules/1/theme
Accept: application/json

###

### Get concept tutorial
# finished OOP refactor
GET http://localhost:3000/api/concepts/1/tutorial
Accept: application/json


### Get concept quizzes
# finished OOP refactor
GET http://localhost:3000/api/concepts/1/quiz
Accept: application/json


### Get concept summary
# finished OOP refactor
GET http://localhost:3000/api/concepts/1/summary
Accept: application/json

###

### Submit quiz answer
POST http://localhost:3000/api/concepts/quiz/1/answer
Content-Type: application/json

{
  "responseType": "single_choice",
  "userId": 9,
  "userAnswerIndices": [0],
  "timeSpent": 19
}

###

### Get module reflection prompt
# finished OOP refactor
GET http://localhost:3000/api/modules/1/reflection
Accept: application/json

###

### Submit module reflection
# finished OOP refactor
POST http://localhost:3000/api/modules/13/reflection
Content-Type: application/json

{
  "reflectionId": 1,
  "userId": 9,
  "answer": "Learnt a lot from this module.",
  "timeSpent": 999
}

###

### Update concept progress (Mark Concept 46 as Complete)
POST http://localhost:3000/api/concepts/1/progress
Content-Type: application/json

{
  "userId": 9,
  "isCompleted": true,
  "timeSpent": 120
}

###

### register a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "john@example.com",
  "username": "johndoe",
  "password": "Password123"
}

### login with email
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "emailOrUsername": "john@example.com",
  "password": "Password123"
}

### login with username
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "emailOrUsername": "johndoe",
  "password": "Password123"
}

### Get current user
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsInVzZXJuYW1lIjoiam9obmRvZSIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzY0NTUzNTcyLCJleHAiOjE3NjQ1NTQ0NzJ9.pM3--n55kJx6SThl2n8aUR1C-6dSrlX-xrJGsil1k7Q

### Logout
POST http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsInVzZXJuYW1lIjoiam9obmRvZSIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzY0NTUzNTcyLCJleHAiOjE3NjQ1NTQ0NzJ9.pM3--n55kJx6SThl2n8aUR1C-6dSrlX-xrJGsil1k7Q


